name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3.6.0
      with:
        repository: "PCSX2/pcsx2"
        fetch-depth: 0
        submodules: false

    - name: Build Dependencies
      shell: cmd
      run: |
        start /w .github\workflows\scripts\windows\build-dependencies.bat

    - name: Create Dependencies Archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a pcsx2-windows-dependencies.7z .\deps

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-windows-dependencies"
        prerelease: false
        title: "Latest Dependencies Build"
        files: |
          pcsx2-windows-dependencies.7z
