name: Create Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deps-update]

jobs:
  create-release:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v7
      with:
        repository: "PCSX2/pcsx2"
        fetch-depth: 0
        submodules: false

    - name: Checkout deps repo
      uses: actions/checkout@v7
      with:
        repository: "PCSX2/pcsx2-windows-dependencies"
        path: deps-repo
        
    - name: Build Dependencies
      shell: cmd
      run: |
        call .github\workflows\scripts\windows\build-dependencies.bat

    - name: Create Dependencies Archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a pcsx2-windows-dependencies.7z .\deps

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $RELEASE="latest-windows-dependencies"

        cd deps-repo
        git push origin --delete $RELEASE || $true
        gh release delete $RELEASE --yes || $true
        git tag -f $RELEASE
        git push origin tag $RELEASE --force

        gh release create $RELEASE --latest --title "Latest Dependencies Build"
        gh release upload $RELEASE ../pcsx2-windows-dependencies.7z
