name: Create Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deps-update]

jobs:
  create-release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
      with:
        repository: "PCSX2/pcsx2"
        fetch-depth: 0
        submodules: false

    - name: Build Dependencies
      shell: cmd
      run: |
        start /w .github\workflows\scripts\windows\build-dependencies.bat

    - name: Create Dependencies Archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a pcsx2-windows-dependencies.7z .\deps

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        RELEASE=latest-windows-dependencies
        gh release delete $RELEASE --cleanup-tag --yes --repo PCSX2/pcsx2-windows-dependencies || true

        # Workaround for https://github.com/cli/cli/issues/8458
        # Thank you @soerenkoehler for the following 'fix'
        printf "waiting for tag to be deleted\n"
        while git fetch --tags --prune-tags; git tag -l | grep $RELEASE; do
          sleep 10;
          printf "still waiting...\n"
        done

        gh release create $RELEASE --latest --title "Latest Dependencies Build" --repo PCSX2/pcsx2-windows-dependencies
        gh release upload $RELEASE ./pcsx2-windows-dependencies.7z --repo PCSX2/pcsx2-windows-dependencies
